const C=window.PTA_CONFIG,E=window.PTA_ENGINE,S=window.PTA_SOLUTIONS,$=s=>document.querySelector(s),main=$("#main"),restartBtn=$("#restartBtn");
const safe=(v="")=>String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const customIndustries=JSON.parse(localStorage.getItem("pta_custom_industries")||"[]");
const fresh=()=>({stage:"welcome",user:{},industry:"Healthcare",archetype:null,index:0,answers:{},acknowledged:false,mixedWork:false});
const state=fresh();
function save(){localStorage.setItem("pta_current_draft",JSON.stringify(state))} function toast(m){const e=$("#toast");e.textContent=m;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2200)}
const stageLabels={welcome:"Welcome",organization:"Organization",archetype:"Healthcare Track",confidentiality:"Instructions",questions:"Assessment",review:"Review",results:"Results",packageView:"Recommendations",emailResults:"Email Results"};
const flowSteps=[["organization","Organization"],["archetype","Track"],["confidentiality","Instructions"],["questions","Assessment"],["review","Review"],["results","Results"]];
const stageToStep={organization:0,archetype:1,confidentiality:2,questions:3,review:4,results:5,packageView:5,emailResults:5};
function flowRail(stage){const cur=stageToStep[stage];if(cur===undefined)return "";return flowSteps.map(([key,label],i)=>{const cls=i<cur?"done":i===cur?"active":"";const mark=i<cur?"\u2713":(i+1);const sep=i?'<span class="sep"></span>':"";return `<span class="flow-step ${cls}">${sep}<span class="dot">${mark}</span><span class="label">${label}</span></span>`}).join("")}
const BAND_COLORS={"Baseline":"#cf5b4a","Enhanced":"#e6a70a","Above Average":"#2c74c4","High Performing":"#2f9e63","Tech-Led":"#00a7a0"};
function bandColor(label){return BAND_COLORS[label]||"#00a7a0"}
function gauge(score,band){const r=80,c=2*Math.PI*r,off=c*(1-Math.max(0,Math.min(100,score))/100),col=bandColor(band);return `<div class="gauge"><svg viewBox="0 0 200 200" role="img" aria-label="Program technology score ${score} out of 100"><circle class="gauge-track" cx="100" cy="100" r="${r}"></circle><circle class="gauge-fill" cx="100" cy="100" r="${r}" stroke="${col}" stroke-dasharray="${c.toFixed(1)}" stroke-dashoffset="${off.toFixed(1)}"></circle></svg><div class="gauge-center"><span class="num">${score}</span><span class="den">/ 100</span></div></div>`}
function shell(c,n=false){main.innerHTML=`<section class="card ${n?'narrow':''}">${c}</section>`;main.focus();restartBtn.classList.toggle("hidden",state.stage==="welcome");$("#flowNav").innerHTML=flowRail(state.stage)}
function render(){({welcome,organization,archetype,confidentiality,questions,review,results,packageView,emailResults,admin}[state.stage]||welcome)();scrollTo({top:0,behavior:"smooth"})}
function welcome(){shell(`<p class="eyebrow">Executive technology diagnostic</p><h1>Program Technology Profile Assessment</h1><p class="lead">A structured assessment of how your program uses technology, automation, data, and intelligence to drive performance and scalability.</p><div class="result-grid"><div class="result-card"><strong>42 diagnostic questions</strong><br><span class="muted">Across six weighted technology domains</span></div><div class="result-card"><strong>Healthcare-specific direction</strong><br><span class="muted">Separate Non-Clinical, Clinical, and HIM solution tracks</span></div><div class="result-card"><strong>Evidence-aware recommendation</strong><br><span class="muted">Confidence and validation needs are explicit</span></div></div><div class="button-row"><button id="start" class="button">Start Assessment</button><button id="resume" class="button secondary" ${localStorage.getItem("pta_current_draft")?'':'disabled'}>Resume saved assessment</button></div>`);$("#start").onclick=()=>{state.stage="organization";render()};$("#resume").onclick=()=>{Object.assign(state,JSON.parse(localStorage.getItem("pta_current_draft")));render()}}
function organization(){shell(`<p class="eyebrow">Step 2 · Organization</p><h1>Tell us about the program</h1><form id="org"><label for="email">Work email</label><input id="email" type="email" required value="${safe(state.user.email)}"><label for="company">Company</label><input id="company" required value="${safe(state.user.company)}"><label for="lob">Line of Business</label><input id="lob" required value="${safe(state.user.lob)}"><label for="industry">Industry</label><select id="industry"><option>Healthcare</option>${customIndustries.map(x=>`<option disabled>${safe(x.name)} (draft)</option>`).join("")}</select><div class="button-row"><button class="button">Continue</button><button id="back" type="button" class="button secondary">Back</button></div></form>`);$("#org").onsubmit=e=>{e.preventDefault();state.user={email:$("#email").value.trim(),company:$("#company").value.trim(),lob:$("#lob").value.trim()};state.stage="archetype";save();render()};$("#back").onclick=()=>{state.stage="welcome";render()}}
function archetype(){shell(`<p class="eyebrow">Step 3 · Healthcare work type</p><h1>Which operating model best describes this line of business?</h1><div class="tiles">${Object.entries(C.archetypes).map(([id,a])=>`<button class="tile arch" data-id="${id}"><strong>${a.title}</strong><br><span class="muted">Examples: ${a.examples}</span></button>`).join("")}</div><label class="check-row"><input id="mixed" type="checkbox" ${state.mixedWork?'checked':''}><span>This line of business contains materially different work types.</span></label><p class="privacy-note">Different operating models should be assessed separately rather than blended into one maturity score.</p><button id="back" class="button secondary">Back</button>`);$("#mixed").onchange=e=>state.mixedWork=e.target.checked;document.querySelectorAll(".arch").forEach(b=>b.onclick=()=>{state.archetype=b.dataset.id;state.stage="confidentiality";save();render()});$("#back").onclick=()=>{state.stage="organization";render()}}
function confidentiality(){shell(`<p class="eyebrow">Step 4 · Data handling</p><h1>Confidentiality and responsible evidence use</h1><div class="notice"><strong>Do not upload or enter PHI.</strong><br>Do not include patient identifiers, medical records, credentials, or sensitive personal health information. Redact evidence before attaching it.</div><p>Information will be treated as confidential. Aggregated or anonymized findings may be used for research and service improvement without naming your company.</p><p>Score what is true today. When between levels, choose the lower level. Evidence can include a redacted screenshot, configuration, log, SOP, dashboard, or a clear evidence reference.</p><label class="check-row"><input id="ack" type="checkbox" ${state.acknowledged?'checked':''}><span>I have read and understand the instructions, confidentiality notice, research-use notice, and PHI restriction.</span></label><div class="button-row"><button id="continue" class="button" ${state.acknowledged?'':'disabled'}>Begin assessment</button><button id="back" class="button secondary">Back</button></div>`);$("#ack").onchange=e=>{$("#continue").disabled=!e.target.checked};$("#continue").onclick=()=>{state.acknowledged=true;state.stage="questions";save();render()};$("#back").onclick=()=>{state.stage="archetype";render()}}
const list=()=>C.domains.flatMap((d,di)=>d.questions.map((q,qi)=>({...q,domain:d,di,qi})));
function questions(){const qs=list(),x=qs[state.index],a=state.answers[x.id]||{},pct=Math.round((state.index/42)*100);shell(`<div class="progress-wrap"><div class="progress-label"><span>Domain ${x.di+1} of 6 · ${x.domain.id} ${x.domain.name}</span><span>Question ${x.qi+1} of 7</span></div><div class="progress" aria-label="Assessment progress"><span style="width:${pct}%"></span></div></div><div class="question-meta"><span>${x.id}</span><span>Domain weight ${x.domain.weight}%</span></div><h1>${safe(x.question)}</h1><p class="artifact-hint"><strong>Suggested evidence:</strong> ${safe(x.artifactHint)}</p><form id="qform"><fieldset><legend class="eyebrow">Choose the statement that best describes today</legend><div class="scores">${[1,2,3].map(n=>{const nm={1:"Yellow — Human-led",2:"Green — Tech-supported",3:"Blue — Tech-led / governed"},cl={1:"yellow",2:"green",3:"blue"};return `<label class="score-option"><input type="radio" name="score" value="${n}" ${a.score==n?'checked':''} required><span><strong><i class="score-dot ${cl[n]}"></i>${nm[n]}</strong><br>${safe(x.anchors[state.archetype][n])}</span></label>`}).join("")}</div></fieldset><details class="evidence-panel" ${a.note||a.artifactName?'open':''}><summary>Add optional evidence</summary><div class="upload-box"><label for="artifact">Redacted evidence artifact</label><input id="artifact" type="file" accept=".pdf,.png,.jpg,.jpeg,.doc,.docx,.xls,.xlsx,.txt"><p class="privacy-note">Prototype: filename only. Do not select files containing PHI.</p>${a.artifactName?`<p>Selected: ${safe(a.artifactName)}</p>`:""}</div><label for="note">Evidence note or reference</label><textarea id="note" rows="3">${safe(a.note||"")}</textarea></details><div class="sticky-actions"><button id="prev" type="button" class="button secondary" ${state.index?'':'disabled'}>Previous</button><button class="button">${state.index===41?'Review assessment':'Save & next'}</button></div></form>`);$("#qform").onsubmit=e=>{e.preventDefault();const f=$("#artifact").files[0];state.answers[x.id]={score:Number(new FormData(e.target).get("score")),note:$("#note").value.trim(),artifactName:f?.name||a.artifactName||""};if(state.index===41)state.stage="review";else state.index++;save();render()};$("#prev").onclick=()=>{state.index--;render()}}
function coverage(){return Math.round(Object.values(state.answers).filter(a=>a.note||a.artifactName).length/42*100)}
function review(){shell(`<p class="eyebrow">Step 6 · Review</p><h1>Confirm the assessment before scoring</h1><p class="lead">All six domains should be complete. Evidence coverage is separate from maturity.</p><div class="result-grid">${C.domains.map((d,i)=>{const done=d.questions.filter(q=>state.answers[q.id]?.score).length;return `<button class="result-card review-domain" data-i="${i*7}"><strong>${d.id} ${done===7?'✓':'Incomplete'}</strong><br>${safe(d.name)}<br><span class="muted">${done}/7 answered</span></button>`}).join("")}</div><div class="notice"><strong>Evidence coverage: ${coverage()}%</strong><br>${coverage()>=85?'High confidence coverage.':coverage()>=70?'Moderate confidence coverage; targeted validation may be recommended.':'Low confidence coverage; a deep-dive assessment will be recommended.'}</div>${state.mixedWork?`<p class="flag"><strong>Mixed operating model noted.</strong> Complete separate assessments for each materially different archetype.</p>`:""}<label class="check-row"><input id="confirm" type="checkbox"><span>I confirm these responses reflect the program today and are ready for indicative scoring.</span></label><div class="button-row"><button id="score" class="button" disabled>Generate executive results</button><button id="back" class="button secondary">Back to assessment</button></div>`);document.querySelectorAll(".review-domain").forEach(b=>b.onclick=()=>{state.index=Number(b.dataset.i);state.stage="questions";render()});$("#confirm").onchange=e=>$("#score").disabled=!e.target.checked;$("#score").onclick=()=>{saveSubmission();state.stage="results";save();render()};$("#back").onclick=()=>{state.stage="questions";state.index=41;render()}}
function result(){return E.evaluate(state)} function packageName(p){return `${p.code} — ${p.name}`} function actions(r){return [...S[state.archetype][r.finalPackage.code]].sort((a,b)=>(a.domain===r.lowestDomain.id?-1:0)-(b.domain===r.lowestDomain.id?-1:0))}
function results(){
 const r=result(),road=actions(r),shown=road.slice(0,9),narrative=`${state.user.company} achieved a Program Technology Profile Score of ${r.programScore}, placing the program in the ${r.programMaturity} maturity range. The recommended direction is ${packageName(r.finalPackage)}, with ${r.lowestDomain.name} as the primary technology focus. Assessment confidence is ${r.confidenceLevel} at ${r.confidenceScore}%; ${r.assessmentDisposition.toLowerCase()}${r.assessmentDisposition==="Recommendation Ready"?".":" before the final technology roadmap is confirmed."}`;
 localStorage.setItem("pta_last_result",JSON.stringify({...r,user:state.user,archetype:state.archetype,createdAt:new Date().toISOString()}));
 shell(`<p class="eyebrow">Assessment complete</p><h1>${safe(state.user.company)}</h1><p>${safe(state.user.lob)} · ${r.healthcareTrack}</p>
 <section class="hero-result">
  <div class="score-panel">
   <span class="metric-label" style="color:#9fc0d1">Program Technology Score</span>
   ${gauge(r.programScore,r.programMaturity)}
   <span class="maturity-chip"><span class="swatch" style="background:${bandColor(r.programMaturity)}"></span>${r.programMaturity}</span>
  </div>
  <div class="metric-panel">
   <div><span class="metric-label">Recommended Package</span><h2>${packageName(r.finalPackage)}</h2></div>
   <div><span class="metric-label">Primary Focus</span><h2>${r.lowestDomain.id}</h2><strong>${safe(r.lowestDomain.name)}</strong></div>
   <div><span class="metric-label">Assessment Confidence</span><h2>${r.confidenceScore}%</h2><strong>${r.confidenceLevel}</strong></div>
   <div><span class="metric-label">Disposition</span><h2>${r.assessmentDisposition}</h2></div>
  </div>
 </section>
 ${r.complianceCaps.map(x=>`<p class="flag"><strong>Healthcare Governance Gate:</strong> ${safe(x.reason)}</p>`).join("")}
 <details open><summary>Why this recommendation?</summary><div class="details-body"><ul><li><strong>Base package:</strong> ${packageName(r.basePackage)} — ${r.basePackageReason}</li><li><strong>Domain override:</strong> ${r.triggeredOverrides.length?r.triggeredOverrides.map(x=>safe(x.rule)).join(", "):"None"}</li><li><strong>Governance cap:</strong> ${r.complianceCaps.length?r.complianceCaps.map(x=>safe(x.gate)).join(", "):"None"}</li><li><strong>Final direction:</strong> ${packageName(r.finalPackage)}</li></ul><p>${safe(r.recommendationExplanation)}</p></div></details>
 <details><summary>Where are the biggest technology opportunities?</summary><div class="details-body"><div class="domain-table" role="table" aria-label="Domain maturity profile">${[...r.domainResults].sort((a,b)=>b.score-a.score).map((d,i)=>`<div class="domain-row" role="row"><span>${d.id} ${safe(d.name)} ${d.id===r.lowestDomain.id?'<strong>— Primary focus</strong>':''}</span><span><strong>${d.score}</strong> · ${d.maturity} · Rank ${i+1}</span></div>`).join("")}</div><p>Strongest: ${r.strongestDomain.id} — ${r.strongestDomain.name}<br>Yellow domains: ${r.yellowCount} · Blue domains: ${r.blueCount}</p></div></details>
 <details open><summary>Your priority roadmap</summary><div class="details-body">${roadmap(shown)}<button id="full" class="button secondary">View Full Solution Package</button></div></details>
 <details open><summary>Further analysis</summary><div class="details-body"><p><strong>Evidence coverage:</strong> ${r.evidenceCount}/42 (${r.confidenceScore}%) · ${r.confidenceLevel}</p>${r.assessmentDisposition!=="Recommendation Ready"?`<h3>${r.recommendedDeepDive.title} Recommended</h3><p>${r.furtherAnalysisTriggers.map(t=>safe(t.detail)).join(" ")}</p><ul>${r.recommendedDeepDive.scope.map(x=>`<li>${x}</li>`).join("")}</ul>`:'<p>The evidence supports moving into solution validation and planning.</p>'}</div></details>
 <details><summary>Executive summary</summary><div class="details-body"><p>${safe(narrative)}</p><p class="muted">Benchmark data not yet available.</p></div></details>
 <section class="keep-copy"><p class="eyebrow">Keep a copy</p><h2>Retain your executive assessment results</h2><p class="privacy-note">Results contain assessment findings only. Uploaded evidence and evidence notes are not included in email or the executive report.</p><div class="action-grid"><button id="email" class="button">Email My Results</button><button id="report" class="button secondary">Download Executive Report</button><button id="csv" class="button secondary">Download CSV</button><button id="fullBottom" class="button secondary">View Full Solution Package</button><button id="review" class="button secondary">Review Assessment</button></div></section>`);
 $("#full").onclick=$("#fullBottom").onclick=()=>{state.stage="packageView";render()};$("#email").onclick=()=>{state.stage="emailResults";render()};$("#report").onclick=()=>downloadReport(r,road,narrative);$("#csv").onclick=()=>download(r,road);$("#review").onclick=()=>{state.stage="review";render()};
}
function roadmap(items){return ["Immediate","Near-Term","Roadmap","Ongoing","Innovation","Strategic"].map(p=>{const a=items.filter(x=>x.priority===p);return a.length?`<h3>${p}</h3><div class="roadmap-grid">${a.map(x=>`<article class="roadmap-card"><span class="priority priority-${p.toLowerCase().replace(/[^a-z]/g,'')}">${p}</span><strong>${safe(x.component)}</strong><small>${x.domain}</small><p>${safe(x.description)}</p><details class="component-details"><summary>View rationale and guardrails</summary><p><strong>Rationale:</strong> ${safe(x.rationale)}</p><p><strong>Expected outcome:</strong> ${safe(x.expectedOutcome)}</p><p><strong>Dependencies:</strong> ${x.dependencies.map(safe).join("; ")}</p><p><strong>Healthcare guardrails:</strong> ${x.guardrails.map(safe).join("; ")}</p><p><strong>Suggested metrics:</strong> ${x.metrics.map(safe).join("; ")}</p></details></article>`).join("")}</div>`:""}).join("")}
function packageView(){const r=result();shell(`<p class="eyebrow">Detailed recommendation</p><h1>${packageName(r.finalPackage)}</h1><p class="lead">${r.healthcareTrack}</p><p><strong>Primary domain focus:</strong> ${r.primarySolutionFocus}</p><p>${safe(r.recommendationExplanation)}</p><div class="filter-row" role="group" aria-label="Filter roadmap by domain">${["All","D1","D2","D3","D4","D5","D6"].map(x=>`<button class="button secondary filter" data-domain="${x}">${x}</button>`).join("")}</div><div id="fullRoadmap">${roadmap(actions(r))}</div><div class="button-row"><button id="back" class="button">Back to Executive Results</button></div>`);document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{$("#fullRoadmap").innerHTML=roadmap(b.dataset.domain==="All"?actions(r):actions(r).filter(x=>x.domain===b.dataset.domain))});$("#back").onclick=()=>{state.stage="results";render()}}
function download(r,road){const rows=[["Assessment","Program Technology Profile Assessment"],["Company",state.user.company],["Email",state.user.email],["Line of Business",state.user.lob],["Healthcare Track",r.healthcareTrack],["Date",new Date().toISOString().slice(0,10)],["Program Score",r.programScore],["Maturity",r.programMaturity],["Base Package",packageName(r.basePackage)],["Domain Override",r.triggeredOverrides.map(x=>x.rule).join("; ")||"None"],["Governance Cap",r.complianceCaps.map(x=>x.gate).join("; ")||"None"],["Final Package",packageName(r.finalPackage)],["Lowest Domain",r.primarySolutionFocus],["Assessment Confidence",`${r.confidenceScore}% — ${r.confidenceLevel}`],["Assessment Disposition",r.assessmentDisposition],["Recommended Deep Dive",r.recommendedDeepDive.title],[],["Domain","Weight","Score","Maturity"],...r.domainResults.map(d=>[`${d.id} ${d.name}`,`${d.weight}%`,d.score,d.maturity]),[],["Priority","Action","Domain","Description"],...road.map(x=>[x.priority,x.component,x.domain,x.description])];const csv=rows.map(row=>row.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download=`${state.user.company.replace(/[^a-z0-9]+/gi,"-")}-executive-assessment.csv`;a.click();URL.revokeObjectURL(a.href)}
function approvedResultPayload(email){const r=result(),road=actions(r);return{email,company:state.user.company,lineOfBusiness:state.user.lob,healthcareTrack:r.healthcareTrack,assessmentDate:new Date().toISOString().slice(0,10),programScore:r.programScore,maturity:r.programMaturity,recommendedPackage:packageName(r.finalPackage),primaryFocus:r.primarySolutionFocus,confidence:`${r.confidenceScore}% — ${r.confidenceLevel}`,disposition:r.assessmentDisposition,recommendedFurtherAnalysis:r.assessmentDisposition==="Recommendation Ready"?"None":r.recommendedDeepDive.title,immediatePriorities:road.filter(x=>["Immediate","Ongoing"].includes(x.priority)).slice(0,5).map(x=>x.component)}}
function saveSubmission(){try{fetch("/api/save-results",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(approvedResultPayload(state.user.email))}).catch(()=>{})}catch(e){}}
function emailResults(){const r=result();shell(`<p class="eyebrow">Email results</p><h1>Send this assessment summary to:</h1><form id="emailForm"><label for="resultEmail">Email address</label><input id="resultEmail" type="email" required value="${safe(state.user.email)}"><div class="email-preview"><strong>${safe(state.user.company)}</strong><br>${r.programScore}/100 — ${r.programMaturity}<br>${packageName(r.finalPackage)}<br>${r.primarySolutionFocus}</div><p class="privacy-note"><strong>Privacy reminder:</strong> Results contain assessment findings only. Uploaded artifacts, PHI, and evidence notes are not included.</p><div id="sendStatus" role="status" aria-live="polite"></div><div class="button-row"><button id="send" class="button">Send Results</button><button id="back" type="button" class="button secondary">Return to Results</button></div></form>`);$("#back").onclick=()=>{state.stage="results";render()};$("#emailForm").onsubmit=async e=>{e.preventDefault();const email=$("#resultEmail").value.trim(),send=$("#send"),status=$("#sendStatus");send.disabled=true;send.textContent="Sending…";status.innerHTML="";try{const response=await fetch("/api/email-results",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(approvedResultPayload(email))});if(!response.ok)throw new Error("delivery failed");status.innerHTML=`<div class="success-state"><strong>Results Sent</strong><p>Your Program Technology Profile Assessment has been sent to <a href="mailto:${safe(email)}">${safe(email)}</a>.</p></div>`;send.classList.add("hidden")}catch(error){status.innerHTML=`<div class="error-state"><strong>We couldn't send your results.</strong><p>Your assessment is still available on this page. Email delivery must be configured on the deployed server, or you can try again.</p></div>`;send.disabled=false;send.textContent="Try Again"}}}
function downloadReport(r,road,narrative){const grouped=["Immediate","Near-Term","Roadmap","Ongoing","Innovation","Strategic"].map(p=>`<h2>${p}</h2><ol>${road.filter(x=>x.priority===p).map(x=>`<li><strong>${safe(x.component)}</strong> (${x.domain}) — ${safe(x.description)}</li>`).join("")}</ol>`).join("");const html=`<!doctype html><html><head><meta charset="utf-8"><title>Executive Assessment Report</title><style>body{font:16px/1.55 Arial;color:#172936;max-width:900px;margin:40px auto;padding:20px}h1,h2{color:#003b5c}.hero{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.box{border:1px solid #dce6eb;border-radius:10px;padding:16px}.muted{color:#617482}@media print{body{margin:0}.hero{grid-template-columns:repeat(3,1fr)}}@media(max-width:650px){.hero{grid-template-columns:1fr}}</style></head><body><p class="muted">HIMAP Program Technology Profile Assessment</p><h1>${safe(state.user.company)}</h1><p>${safe(state.user.lob)} · ${r.healthcareTrack} · ${new Date().toISOString().slice(0,10)}</p><div class="hero"><div class="box"><small>PROGRAM SCORE</small><h2>${r.programScore}/100</h2>${r.programMaturity}</div><div class="box"><small>RECOMMENDED PACKAGE</small><h2>${packageName(r.finalPackage)}</h2></div><div class="box"><small>CONFIDENCE</small><h2>${r.confidenceScore}%</h2>${r.confidenceLevel}</div></div><h2>Primary Focus</h2><p>${r.primarySolutionFocus}</p><h2>Assessment Disposition</h2><p>${r.assessmentDisposition}</p><h2>Executive Summary</h2><p>${safe(narrative)}</p><h2>Domain Profile</h2>${r.domainResults.map(d=>`<p><strong>${d.id} ${safe(d.name)}</strong>: ${d.score}/100 — ${d.maturity}</p>`).join("")}<h2>Technology Roadmap</h2>${grouped}<h2>Further Analysis</h2><p>${r.assessmentDisposition==="Recommendation Ready"?"No additional deep dive triggered.":r.recommendedDeepDive.title}</p><p class="muted">This report contains assessment findings only. Uploaded evidence and evidence notes are excluded.</p></body></html>`;const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([html],{type:"text/html"}));a.download=`${state.user.company.replace(/[^a-z0-9]+/gi,"-")}-executive-report.html`;a.click();URL.revokeObjectURL(a.href)}
function admin(){shell(`<p class="eyebrow">Administrator</p><h1>Industry configuration</h1><p>Healthcare is published. Future-industry drafts remain local in this prototype.</p><form id="add"><label for="newIndustry">New industry</label><input id="newIndustry" required><label for="desc">Description</label><textarea id="desc"></textarea><button class="button">Add draft</button></form><div class="admin-list"><div class="admin-item"><strong>Healthcare</strong><br>Published · 3 archetypes · 42 questions</div>${customIndustries.map((x,i)=>`<div class="admin-item"><strong>${safe(x.name)}</strong><br>${safe(x.description)}<button class="button danger del" data-i="${i}">Delete</button></div>`).join("")}</div><button id="exit" class="button secondary">Return</button>`);$("#add").onsubmit=e=>{e.preventDefault();customIndustries.push({name:$("#newIndustry").value.trim(),description:$("#desc").value.trim()});localStorage.setItem("pta_custom_industries",JSON.stringify(customIndustries));render()};document.querySelectorAll(".del").forEach(b=>b.onclick=()=>{customIndustries.splice(Number(b.dataset.i),1);localStorage.setItem("pta_custom_industries",JSON.stringify(customIndustries));render()});$("#exit").onclick=()=>{state.stage="welcome";render()}}
$("#adminNav").onclick=()=>{const p=prompt("Enter the prototype admin password:");if(p==="change-me"){state.stage="admin";render()}else if(p!==null)toast("Incorrect password")};restartBtn.onclick=()=>{if(confirm("Start over and clear current answers?")){Object.assign(state,fresh());localStorage.removeItem("pta_current_draft");render()}};render();
