"use client";
import { useEffect,useState } from "react";
type Assessment={id:string;company:string;line_of_business:string;status:string;created_at:string;updated_at:string};
export function AdminCleanup(){
  const [rows,setRows]=useState<Assessment[]>([]);const [page,setPage]=useState(0);const [more,setMore]=useState(false);const [selected,setSelected]=useState<Assessment|null>(null);const [confirmation,setConfirmation]=useState("");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [refresh,setRefresh]=useState(0);
  useEffect(()=>{let active=true;setBusy(true);fetch(`/api/admin/cleanup?page=${page}`,{cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error();return r.json();}).then(d=>{if(active){setRows(d.assessments);setMore(d.hasMore);}}).catch(()=>{if(active)setMessage("Could not load assessments. Refresh this page to retry.");}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[page,refresh]);
  async function remove(event:React.FormEvent){event.preventDefault();if(!selected)return;setBusy(true);setMessage("");try{const r=await fetch("/api/admin/cleanup",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({assessmentId:selected.id,confirmation,updatedAt:selected.updated_at})});const d=await r.json();if(!r.ok){setMessage(d.error);return;}setMessage(`Assessment ${selected.id} deleted. Its answers, results, recommendations, delivery logs, and pending notification were removed. The login account was preserved.`);setSelected(null);setConfirmation("");setRefresh(n=>n+1);}catch{setMessage("Could not confirm deletion. Refresh the list before retrying.");}finally{setBusy(false);}}
  return <section className="section"><h2>Delete a specific assessment</h2><div className="notice warning">Owner only. Deletion permanently removes the selected assessment and its saved answers/results. Download a copy first if needed. It does not delete the respondent’s login account or recall emailed/downloaded copies.</div>{message&&<p role="status">{message}</p>}{busy&&<p role="status">Please wait…</p>}<div className="review-list">{rows.map(a=><article className="card" key={a.id}><strong>{a.company} · {a.line_of_business}</strong><p>{a.status} · {new Date(a.created_at).toLocaleDateString()}<br/><code>{a.id}</code></p><button className="button secondary" disabled={busy} onClick={()=>{setSelected(a);setConfirmation("");setMessage("");}}>Select for deletion</button></article>)}</div>{!busy&&!rows.length&&<p>No assessments on this page.</p>}<div className="button-row"><button className="button secondary" disabled={busy||page===0} onClick={()=>{setPage(p=>p-1);setSelected(null);}}>Previous</button><button className="button secondary" disabled={busy||!more} onClick={()=>{setPage(p=>p+1);setSelected(null);}}>Next</button></div>{selected&&<form className="notice warning" onSubmit={remove}><h3>Confirm permanent deletion</h3><p>{selected.company} · {selected.line_of_business}<br/>Assessment: <code>{selected.id}</code></p><label htmlFor="delete-confirmation">Type the full assessment reference above</label><input id="delete-confirmation" autoComplete="off" required value={confirmation} onChange={e=>setConfirmation(e.target.value)}/><div className="button-row"><button className="button" disabled={busy||confirmation!==selected.id}>Permanently delete this assessment</button><button className="button secondary" type="button" disabled={busy} onClick={()=>{setSelected(null);setConfirmation("");}}>Cancel</button></div></form>}</section>;
}
